#!/usr/bin/env node
// Extracts canonical Anno 117 game data from the anno-mods/anno-117-calculator
// params.js (a JSON dump scraped from the game's asset XML, dated 2025-11-21)
// and emits a TypeScript module our planner consumes directly.
//
// Run: node scripts/extract.mjs <path-to-params.js> > src/data/game.ts
import fs from 'node:fs';

const PARAMS_PATH = process.argv[2] ?? '/tmp/anno117-data/anno-117-calculator/js/params.js';
const raw = fs.readFileSync(PARAMS_PATH, 'utf8');
const json = raw.replace(/^if\(window\.params == null\)window\.params=/, '').replace(/;\s*$/, '');
const p = JSON.parse(json);

// Workforce GUID -> tier id used in our app
const WORKFORCE_TIER = {
  2181: 'liberti',
  2184: 'plebeians',
  2185: 'equites',
  2186: 'patricians',
  2192: 'waders',
  2196: 'smiths',
  2197: 'aldermen',
  2198: 'mercators',
  2199: 'nobles',
};
const DENARII_GUID = 1010017;

const REGION_FROM_NAME = {
  Roman: 'latium',
  Celtic: 'albion',
};

// Build product lookup
const products = {};
for (const prod of p.products) {
  products[prod.guid] = {
    guid: prod.guid,
    name: prod.locaText?.english ?? prod.name,
    regions: (prod.associatedRegions ?? []).map(r => REGION_FROM_NAME[r] ?? r),
    isAbstract: !!prod.isAbstract,
    isConstructionMaterial: !!prod.isConstructionMaterial,
    iconPath: prod.iconPath,
  };
}

// Fertilities
const fertilities = {};
for (const f of p.fertilities) {
  fertilities[f.guid] = {
    guid: f.guid,
    name: f.locaText?.english ?? f.name,
    regions: (f.regions ?? []).map(r => REGION_FROM_NAME[r] ?? r),
    iconPath: f.iconPath,
  };
}

// Factories — only keep those that have at least one output that is a non-abstract product
const factories = {};
for (const f of p.factories) {
  const outputs = (f.outputs ?? []).filter(o => products[o.product] && !products[o.product].isAbstract);
  if (outputs.length === 0) continue; // service buildings, residences, etc.
  const inputs = (f.inputs ?? []).filter(i => products[i.product]);

  let denarii = 0;
  let workforceTier = null;
  let workforceAmount = 0;
  for (const m of f.maintenances ?? []) {
    if (m.product === DENARII_GUID) denarii = m.amount;
    else if (WORKFORCE_TIER[m.product]) {
      workforceTier = WORKFORCE_TIER[m.product];
      workforceAmount = m.amount;
    }
  }

  const regions = (f.associatedRegions ?? []).map(r => REGION_FROM_NAME[r] ?? r);
  factories[f.guid] = {
    guid: f.guid,
    name: f.locaText?.english ?? f.name,
    cycleTime: f.cycleTime,
    regions,
    inputs: inputs.map(i => ({ product: i.product, amount: i.amount })),
    outputs: outputs.map(o => ({ product: o.product, amount: o.amount })),
    denarii,
    workforceTier,
    workforceAmount,
    fertility: f.neededFertility || 0,
    needsFuelInput: !!f.needsFuelInput,
    iconPath: f.iconPath,
  };
}

// Population tiers
const tiers = {};
for (const lvl of p.populationLevels) {
  const id = WORKFORCE_TIER[lvl.connectedWorkforce];
  if (!id) continue;
  tiers[id] = {
    id,
    guid: lvl.guid,
    name: lvl.locaText?.english ?? lvl.name,
    region: REGION_FROM_NAME[lvl.associatedRegions?.[0]] ?? 'both',
    workforceFactor: lvl.populationToWorkforceFactor,
    iconPath: lvl.iconPath,
  };
}

// Residence needs — used to discover which goods belong to which tier
const residences = p.residenceBuildings.map(r => ({
  guid: r.guid,
  name: r.locaText?.english ?? r.name,
  region: REGION_FROM_NAME[r.associatedRegions?.[0]] ?? 'both',
  populationLevel: r.populationLevel,
  upgradesTo: r.possibleUpgrades?.[0] ?? null,
  needs: (r.needsList ?? []).map(n => ({ need: n.need, rate: n.needConsumptionRate })),
}));

// Needs map. The game stores needs separately from the goods they consume.
// `needProduct` is the product GUID consumed (null for service / non-good needs
// like Faith and Entertainment). `needAttributes.Population` is how many
// residents this need contributes to a residence when satisfied — total
// residence capacity is the sum of these across all met needs.
const needs = {};
for (const n of p.needs ?? []) {
  needs[n.guid] = {
    guid: n.guid,
    name: n.locaText?.english ?? n.name,
    product: n.needProduct ?? null,
    category: n.needCategory ?? null,
    population: n.needAttributes?.Population ?? 0,
    happiness: n.needAttributes?.Happiness ?? 0,
    isBuilding: !!n.isBuilding,
  };
}

// Emit TypeScript
const out = `// AUTO-GENERATED by scripts/extract.mjs from anno-117-calculator params.js (2025-11-21).
// Do not edit by hand — re-run the extractor to refresh.
// Source: https://github.com/anno-mods/anno-117-calculator

export type RegionId = 'latium' | 'albion' | 'both';
export type TierId =
  | 'liberti' | 'plebeians' | 'equites' | 'patricians'
  | 'waders' | 'smiths' | 'aldermen' | 'mercators' | 'nobles';

export interface Product {
  guid: number;
  name: string;
  regions: RegionId[];
  isAbstract: boolean;
  isConstructionMaterial: boolean;
  iconPath: string;
}

export interface Fertility {
  guid: number;
  name: string;
  regions: RegionId[];
  iconPath: string;
}

export interface FactoryIO {
  product: number;
  amount: number;
}

export interface Factory {
  guid: number;
  name: string;
  cycleTime: number; // seconds for one cycle
  regions: RegionId[];
  inputs: FactoryIO[];
  outputs: FactoryIO[];
  denarii: number;          // upkeep per minute
  workforceTier: TierId | null;
  workforceAmount: number;
  fertility: number;        // 0 = none, otherwise a Fertility guid
  needsFuelInput: boolean;
  iconPath: string;
}

export interface PopulationTier {
  id: TierId;
  guid: number;
  name: string;
  region: RegionId;
  workforceFactor: number; // residents → workforce
  iconPath: string;
}

export interface Residence {
  guid: number;
  name: string;
  region: RegionId;
  populationLevel: number;
  upgradesTo: number | null;
  needs: { need: number; rate: number | null }[];
}

export interface Need {
  guid: number;
  name: string;
  /** GUID of the product consumed; null for non-good needs (e.g. Faith). */
  product: number | null;
  /** "Food", "Drink", "Clothing", "Hygiene", "Faith", "Entertainment", etc. */
  category: string | null;
  /** Residents added to a residence when this need is met. */
  population: number;
  happiness: number;
  isBuilding: boolean;
}

export const PRODUCTS: Record<number, Product> = ${JSON.stringify(products, null, 2)};

export const FERTILITIES: Record<number, Fertility> = ${JSON.stringify(fertilities, null, 2)};

export const FACTORIES: Record<number, Factory> = ${JSON.stringify(factories, null, 2)};

export const TIERS: Record<TierId, PopulationTier> = ${JSON.stringify(tiers, null, 2)} as Record<TierId, PopulationTier>;

export const RESIDENCES: Residence[] = ${JSON.stringify(residences, null, 2)};

export const NEEDS: Record<number, Need> = ${JSON.stringify(needs, null, 2)};

// Convenience: producing factories grouped by output product GUID.
export const FACTORIES_BY_OUTPUT: Record<number, number[]> = (() => {
  const m: Record<number, number[]> = {};
  for (const f of Object.values(FACTORIES)) {
    for (const o of f.outputs) {
      (m[o.product] ??= []).push(f.guid);
    }
  }
  return m;
})();
`;

process.stdout.write(out);
